### ISSUE TITLE
[Package] Enable way to pip install private libraries and include in goblet deploy

### ISSUE THREAD

**Issue by anovis** [goblet/goblet#108]
users can currently manually copy libraries, but that is not useful if multiple functions will share a library. 

could include logic to automatically download private libraires and include in zip. 

could also include a `goblet-requirements.txt` which will install/cp libraries locally and include the packages zip

see also https://docs.readthedocs.io/en/stable/guides/private-python-packages.html#installing-private-python-packages

**Comment by amirbtb** [comment]
Hello, this is how I manage to do it.
Let's say my repo is located at **mygithubuser/myrepo** :

- First, I [generate a Github Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
- pass the Github Token to `buildEnvironmentVariables` key in `config.json` 
```
{
    "cloudfunction": {
        "runtime":"python37",
        "buildEnvironmentVariables": {
            "GIT_TOKEN":"YOURGITHUBTOKEN"
        },
        "availableMemoryMb": 512,
        "timeout": "30s",
    }
}
```
- Finally I use the following structure `git+https://${GIT_TOKEN}@github.com/mygithubuser/myrepo` inside the `requirements.txt`

I had a different use case with a repo inside a subfolder of the repository (for example `src`), I used this structure `git+https://${GIT_TOKEN}@github.com/mygithubuser/myrepo/#subdirectory=src`
