### ISSUE TITLE
[Cloud Function] 2nd generation

### ISSUE THREAD

**Issue by anovis** [goblet/goblet#131]
support for new generation of cloud functions. Allow users to toggle between them. 

https://cloud.google.com/blog/products/serverless/introducing-the-next-generation-of-cloud-functions

**Comment by davidyum** [comment]
Posting this link here:
https://cloud.google.com/functions/docs/2nd-gen/2nd-gen-differences

**Comment by anovis** [comment]
support added in release 0.8.0
