### ISSUE TITLE
Goblet destroy - nested resources

### ISSUE THREAD

**Issue by AdeelK93** [goblet/goblet#201]
Hi, loving goblet so far! I get an error when I try to destroy my deployment, at the API gateway step.

> HttpError 400 when requesting https://apigateway.googleapis.com/v1/projects/myproject/locations/global/apis/goblet-cloud-run-test?alt=json returned "Resource '"projects/myproject/locations/global/apis/goblet-cloud-run-test"' has nested resources". Details: "Resource '"projects/myproject/locations/global/apis/goblet-cloud-run-test"' has nested resources"

I get the same error when going through the UI, and need to delete the nested resources individually. Perhaps this could be automated? Thanks!

**Comment by anovis** [comment]
I have tried a few times to automate this actually and it works 50% of the time for some reason. Usually if you run `goblet destroy` a second time it will complete successfully. 

here is the logic where it should wait for the api configs to delete before deleting the api. 
https://github.com/goblet/goblet/blob/main/goblet/resources/routes.py#L241

looking at it now, it looks like it is just using the `wait_for_operation` on the last resp vs all of the responses, which might be the cause of this bug. 

thanks for bringing this up and will try to see if i can fix it.
