### ISSUE TITLE
Cloud Run Jobs customization

### ISSUE THREAD

**Issue by AdeelK93** [goblet/goblet#260]
Hi I'm trying to customize a few things about the cloud run jobs deployment, but can't find any documentation or examples on how to change:
* cpu/memory resources
* timeout
* number of retries
* VPC connector
* total number of tasks

Would love some help! Thanks

**Comment by anovis** [comment]
Thanks for the issue and will add some more documentation to the [example](https://github.com/goblet/goblet/blob/main/examples/example_cloudrun_job/config.json) config. Most fields can be set in either the job spec or job container fields. https://cloud.google.com/run/docs/reference/rest/v1/TaskSpec for a reference. 

The total number of tasks is calculated by goblet based on the number of task_id set for the specific job. 
ie 

app.job("test", task_id=0) 
app.job("test", task_id=1) 
app.job("test", task_id=2)

will result in number of tasks to be 3.

**Comment by rasnes** [comment]
By looking at the code it was possible to see how one could change this values by directly controlling the YAML that goblet deploys the Job with: https://github.com/goblet/goblet/blob/0c0146a0a54eacff48fff4555e14c4d60f7e20f0/goblet/resources/jobs.py#L46-L88

For example, I now deploy with this in my `.goblet/config.yaml`:

```json
{
	...,
    "job_spec": {
        "serviceAccountName": "<sa-name>@<project-id>.iam.gserviceaccount.com",
        "timeoutSeconds": "3600",
        "maxRetries": 3
    },
    "job_container": {
        "resources": {
            "limits": {
                "memory": "8Gi",
                "cpu": "2000m"
            }
        },
        "env": [
            {
                "name": "GOOGLE_PROJECT",
                "value": "<project-id>"
            },
            {
                "name": "GOOGLE_ENV",
                "value": "test"
            }
        ]
    }
}
```

I believe you can set the VPC connector in this YAML as well, but haven't checked.

**Comment by anovis** [comment]
@rasnes thanks for the example. i have updated the example `config.json` and will try to add more examples there going forward as it is a pain to read the code or go through the gcp docs to figure out where to place what. 

also it looks like the vpc connector info is actually set in the metadata fields, so added a pr that allows those fields to be passed in as well (#262 )

**Comment by AdeelK93** [comment]
Thank you both, this was very helpful!
`job_annotations` - who woulda guessed.
