### ISSUE TITLE
Cloud run jobs not correctly interfacing with cloud logging

### ISSUE THREAD

**Issue by AdeelK93** [goblet/goblet#264]
When using logging like in the cloud run jobs tutorial, like: `app.log.info(f"job...{id}")`

In cloud logging, this is being interpreted as print statements / stdout, not actually structured cloud logging.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/16856016/196294915-86c0f8ad-ce36-406a-a421-1aab1dc4990b.png">

Not a huge deal, but structured logging is nice to have

**Comment by anovis** [comment]
I had given an initial shot in #191 to fix #159 , but the one issue that i haven't fixed is that when deploying, the logs were uploaded to stackdriver as well. not sure if thats the end of the world, but will continue to look into it.

**Comment by AdeelK93** [comment]
Thanks @anovis!
