### ISSUE TITLE
[Pydantic] Add path parameter parsing on Pydantic plugin

### ISSUE THREAD

**Issue by cs-hua** [goblet/goblet#271]
Could we add the Pydantic model parsing for query_params too, just like we do in request_body? So it would be like:
```
@app.route(
    "/interaction_results",
    methods=["GET"],
    query_param=SOME_PYDANTIC_MODEL,
)
```

**Comment by anovis** [comment]
hmm how would this look in practice, since query params can't be objects.
right now it is supported by a list of param dicts that have the type and name
```
query_params=[
                {"name": "test", "type": "string", "required": True},
                {"name": "test2", "type": "string", "required": True},
            ]
```

**Comment by cs-hua** [comment]
I'm imagining we just pass the class directly, and simply only accept it if the class represents a basic dictionary, something like below:
```
class Foo(BaseModel):
  test: string
  test2: Optional[int]

......
query_params=Foo
```

 The current query params look almost exactly like what's generated by calling json_schema() on the Pydantic class, except the "required" field, so we will need to do some parsing there like I do on [ITF-service](https://github.com/premisedata/itf-service/blob/main/itf/adapters/clients/qc_modules_client.py#L31) if we want to match with the existing format.

I think the marshmallow plugin already does something similar. This might be what we are looking for?
https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/ext/marshmallow/__init__.py#L186

**Comment by anovis** [comment]
ah getting close (ie works for marshamallow), but getting conflicts now with pydantic. will continue to play around with it
