### ISSUE TITLE
Bigquery integration

### ISSUE THREAD

**Issue by AdeelK93** [goblet/goblet#280]
I'd like to propose a new integration/decorator - bigquery. [Remote functions are recently GA](https://cloud.google.com/bigquery/docs/reference/standard-sql/remote-functions).

Basically, this would be similar to the `app.post` decorator, but also:
* create a cloud_resource connection (if it doesn't exist), sharing the name of the goblet app
* register the cloud function or cloud run as a remote function in bigquery
* require the user to provide the name of the BQ remote function to create, as well as the function type signature

Interested in feedback on the idea!

**Comment by anovis** [comment]
@AdeelK93 we are working on adding this feature at the moment. Do you have a specific use case in mind already?

**Comment by AdeelK93** [comment]
Awesome! My use-case: we store big data in BigQuery, but keep a lot of metadata in other systems, that are either only accessible via either API or a database flavor not yet supported by federated queries. This feature would allow me to correlate such data with metadata, joining SQL to the output of a Python function in a real-time manner.

Another related use-case would involve working with other real-time APIs, like economic data. Goblet let's us have reproducible and easy builds for such a pattern.

Let me know if there's anything else I can do to help with development!

**Comment by anovis** [comment]
@AdeelK93 this feature is out in the latest release of `0.10.0` . Let us know how it goes and if any changes/ improvements are needed!
