### ISSUE TITLE
Update example `main.py`

### ISSUE THREAD

**Issue by vinnyricciardi** [goblet/goblet#322]
As I go through goblet's examples, here's a running list of nits

- There aren't underscores allowed in [Goblet's function name](https://github.com/goblet/goblet/blob/10ba6ca9951f908676acdeaf190a1d4c011ca371/examples/main.py#L10). Change `app = Goblet(function_name="goblet_example", region="us-central-1")` to `app = Goblet(function_name="goblet-example", region="us-central-1")`

**Comment by anovis** [comment]
Ah good catch. so interestingly underscores are allowed in cloudfunctions, which is what the default example was, but not for cloudrun... I'll change so it is capable for all backends. 

It's also worth adding some validation for the cloudrun name in goblet as well before deploying to provide a better user experience, so ill add that as well.
