### ISSUE TITLE
cloud function gen2 deployment

### ISSUE THREAD

**Issue by Bethket** [goblet/goblet#365]
Hi thanks for the code, I am searching for deployment option for GCP cloud function gen2, Does the support gen2 deployment? thanks

**Comment by anovis** [comment]
@Bethket yes we support cloudfunction gen2. Behind the scenes cloudfunction gen2 uses cloudrun, so I often just use cloudrun instead. 

check the documentation here 

https://goblet.github.io/goblet/build/html/backends.html#cloudfunction

for cloudfunction gen two you just need to specify the backend when you create the Goblet app. 

```
app = Goblet(backend="cloudfunctionv2")
```

for cloudrun 

```
app = Goblet(backend="cloudrun")
```
