### ISSUE TITLE
Support for API Keys for authentication

### ISSUE THREAD

**Issue by nbrandaleone** [goblet/goblet#381]
While API keys are support outdated, they are still useful in some circumstances.  Cloud Endpoints support them, so it would be great if Goblet also supported them.

See: https://cloud.google.com/api-gateway/docs/authenticate-api-keys

**Comment by nbrandaleone** [comment]
My error. I was talking about Cloud Endpoints.  However API Gateway also supports API keys.

**Comment by anovis** [comment]
@nbrandaleone i believe we can use api keys already, by passing in the correct security definition (goblet is mainly a passthrough for the api security definitions), although i have not used api keys myself.

for example in `config.json` you can specify 

```
{
    "securityDefinitions":{
        "your_custom_auth_id":{
            "type": "apiKey",
            "in": "header",
            "name": "X-API-Key",
        }
    }
}
``` 
openapi spec: https://swagger.io/docs/specification/2-0/authentication/api-keys/
goblet config: https://goblet.github.io/goblet/build/html/topics.html#authentication

**Comment by anovis** [comment]
@nbrandaleone let me know if that works for you. in the meantime i will work on adding some more complete examples in the repo.

**Comment by nbrandaleone** [comment]
An example in the documentation would be more than sufficient. 
Thanks!

**Comment by anovis** [comment]
@nbrandaleone checkout #383 . let me know if there is anything missing / any open questions you may have that I can include.
