### ISSUE TITLE
[cloudfunction] Deploy from a Google Cloud Storage URI

### ISSUE THREAD

**Issue by mauriciowittenberg** [goblet/goblet#447]
- When a cloudfunction is created, provide a configuration to pass `sourceArchiveUrl` from [Cloudfunction](https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction)
as the source for Cloudfunction's code

- Upload the code to a custom Google Cloud Storage Bucket with a custom name, as with `GOBLET_BUILD_TAGS` when tagging CloudRun Docker images.

This way a release version can be deployed from the same code on multiple environments.

**Comment by nthings** [comment]
Adding note here for recent discovery. Docs on how to upload files to GCS bucket is not very clear on how to do it with the API: https://cloud.google.com/storage/docs/uploading-objects#permissions-rest to add `--data-binary` on `goblet_gcp_client` as the example there shows for curl you can use the `media_body` property. Like this:

```
VersionedClients().storage_objects.execute(
    "insert",
    params={
        "bucket": bucket_name,
        "uploadType": "media",
        "media_body": file,
        "body": {
            "name": file,
        },
    },
)
```
