### ISSUE TITLE
PubSub Emulator Example non functional

### ISSUE THREAD

**Issue by fbormann** [goblet/goblet#480]
Hi folks, I am trying to run the steps described in the README.md of the examples/example_pubsub_emulator folder (created at this PR https://github.com/goblet/goblet/pull/422) but I am getting the following error when I run `goblet local --extras` command:

<img width="1261" alt="image" src="https://github.com/goblet/goblet/assets/2985027/6b8dbd67-126e-466d-81eb-61c7f45a1f2a">

It asks to refresh my credentials, why would that be the case?
Am I missing some step? (I did add the environment variables before that)

**Comment by anovis** [comment]
goblet uses a gcp client by default when spinning up, which is looking for local gcp credentials. if you do not need any connections to gcp you can use `export G_MOCK_CREDENTIALS=True` which will use mocked credentials.
