### ISSUE TITLE
@app.job() raising Job not found after deployment

### ISSUE THREAD

**Issue by alissonpelizaro** [goblet/goblet#483]
Hi folks, how are you doing?

We use Goblet a long time in our projects, but it seems the jobs created by app.job() stopped run. It raises "Job {name} not found" on GCP logs.

Here is an implementation example:

```python
# app_prepare.py

from goblet import Goblet, goblet_entrypoint

def run_job():
    return "Yes, we did it!"

app = Goblet(
    backend="cloudrun",
    cors=True,
)

goblet_entrypoint(app)

@app.job("rebuild")
def rebuild(_id: any) -> str:
    app.log.info(f"Starting: {_id}")
    message = run_job()
    app.log.info(f"SUCCESS: {message}")
    return "200"
```

Goblet stage config:
```json
{
    "stages": {
        "app_prepare": {
            "function_name": "app-prepare",
            "main_file" : "app_prepare.py",
            "job_container": {
                "env": [],
                "resources": {
                    "limits": {
                        "memory": "1Gi"
                    }
                },
                "volume_mounts": {
                    "name": "cloudsql",
                    "mount_path": "/cloudsql"
                }
            },
            "job_spec": {
                "volumes": [
                    ...
                ],
            }
        },
    }
}
```

Deployed command:
```sh
goblet deploy -p my-project --location us-central1 --stage app_prepare
```

Deployed succeeded, but the execution fails and we got this error on GCP logs:
```
2024-03-08 10:10:54.474 BRT   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-03-08 10:10:54.474 BRT     return __callback(*args, **kwargs)
2024-03-08 10:10:54.474 BRT            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-08 10:10:54.474 BRT   File "/usr/local/lib/python3.11/site-packages/goblet/cli.py", line 462, in run_job
2024-03-08 10:10:54.478 BRT     app(name, int(task_id))
2024-03-08 10:10:54.478 BRT   File "/usr/local/lib/python3.11/site-packages/goblet/resource_manager.py", line 187, in __call__
2024-03-08 10:10:54.483 BRT     raise e
2024-03-08 10:10:54.483 BRT   File "/usr/local/lib/python3.11/site-packages/goblet/resource_manager.py", line 155, in __call__
2024-03-08 10:10:54.483 BRT     response = self.handlers["jobs"](request, context)
2024-03-08 10:10:54.483 BRT                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-08 10:10:54.483 BRT   File "/usr/local/lib/python3.11/site-packages/goblet/handlers/jobs.py", line 45, in __call__
2024-03-08 10:10:54.486 BRT     raise ValueError(f"Job {name} not found")
2024-03-08 10:10:55.029 BRT Container called exit(1).
2024-03-08 10:10:55.029 BRT ValueError: Job app-prepare-rebuild not found
```

> Goblet version: 0.13.0

No erros found on Cloud Build and deployment console. 
Can you help us to solve that?

**Comment by anovis** [comment]
thanks for the detailed bug description. looking into it now and will report back . I wonder if this is an issue with stages and cloudrun jobs.

**Comment by anovis** [comment]
@alissonpelizaro I was actually able to run your code and it successfully ran for me. 

<img width="608" alt="Screenshot 2024-03-09 at 1 34 32 PM" src="https://github.com/goblet/goblet/assets/3811703/b5cb8a75-ea6e-4956-af15-19ac78a97393">

can you confirm that you are in fact using the correct goblet version in `requirements.txt` 0.13.0, since I remember seeing this issue in an earlier version. 
 
can you also confirm the file structure in the deployed zip file. 

this can be found in `.goblet/app-prepare.zip`


in the previous goblet version if you set the STAGE as an environment variable that fixed this error, but should not be needed in the latest version.

**Comment by alissonpelizaro** [comment]
Hello @anovis,

Yes, I'm testing with the latest version `0.13.1` now.

I have been conducting several tests on this issue and I have realized that the problem occurs when we include custom files globally. For example:

_config.json_:
```json
{
    "custom_files": {
        "include": ["*.json", "*.jsonl"]
    },
   ...
    "stages": {
        ...
    }
}
```

When we are more specific in this declaration, the problem disappear. For instance:

_config.json:_
```json
{
    "custom_files": {
        "include": [
            "app_core/services/files/*.json",
            "app_assets/*.jsonl"
        ]
    },
   ...
    "stages": {
        ...
    }
}
```

I haven't delved deeper to understand why it raises "Job {...} not found." on GCP, but it is indeed happening. If you want to try, just add the first config to your Goblet config.json file.

This workaround (being more specific with the path) works fine for me. This issue could be closed if you don't want to delve deeper into this topic right now.

**Comment by anovis** [comment]
@alissonpelizaro thanks for sharing! i will look into the `custom_files` more over the weekend, since that is certainly not the expected behavior.

**Comment by anovis** [comment]
@alissonpelizaro i was able to replicate the issue. it is very strange! will see if I can find the root of the issue.

**Comment by anovis** [comment]
ah @alissonpelizaro i figured it out. the issue is behind the scenes we modify the config.json to work with stages in the deployment, but then with the *.json in the includes goblet is actually adding config.json back and overriding the goblet changes. so if you add ` "exclude": ["config.json"]` it will work with you *.json includes. 

i will work on a quick fix to goblet to always ignore config.json if it is included by the user.
